// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iotbioxbckuqpbwjjouq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvdGJpb3hiY2t1cXBid2pqb3VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODExMDcsImV4cCI6MjA3MDM1NzEwN30.YQ_fgVRyId1pj_89G8RI9vkH2-OJoQzqXtuULnzDMtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});